### ISSUE TITLE
sMain.luac:175: Bad argument @ 'takePlayerScreenShot' [Expected element at argument 1, got nil]

### ISSUE THREAD

**Issue by bryancsdev** [ruip005/mta_anticheat#3]
Opa amigo gostei bastante do projeto e em testes deu esse erro tmj

**Comment by ruip005** [comment]
A linha foi verificada, e está ausente a passagem de um argumento na estrutura, provocando assim esse aviso no debugscript porém não é grave mas obrigado por abrir a issue!
