### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Derbosik** [ruip005/mta_anticheat#7]
Good thing you're adding into the banlist using the source variable instead of client, resulting in cheaters being able to ban anyone as long as they have the ACL group 👏 

Also, this is not open source although it should, so I am kindly sharing that you're essentially tracking people by saving their serial using a Discord Webhook.

![obrázok](https://github.com/ruip005/mta_anticheat/assets/99475875/708be2c5-8fef-46f7-8862-0e33d9be016e)

**Comment by ruip005** [comment]
I'll fix it in the next update
